# Maven


# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
- main

pool: Nodepool


steps:
- task: PowerShell@2
  inputs:
    filePath: './db_env_managment_scripts/export_db_to_bacpac.ps1'